### ISSUE TITLE
Feature request: Offline installation

### ISSUE THREAD

**Issue by ReportX** [dbuezas/lgt8fx#240]
Please provide a script for offline installation when there is no computers with online connection nearby.
Thanks

**Comment by dbuezas** [comment]
One only needs to put the contents of the zip file (in releases) inside the hardware folder of the Arduino sketch folder.
Since its path depends on the OS and it is user configurable, I am not aware of any easy way of finding it inside a script, so I suggest you create your own, adapted to the specific configuration of your target computers :).
