### ISSUE TITLE
Undocumented registers?

### ISSUE THREAD

**Issue by LaZsolt** [dbuezas/lgt8fx#78]
I found two IO registers, which seems to me, are undocumented.

![kép](https://user-images.githubusercontent.com/60486174/107846427-0479e300-6de4-11eb-8c5a-18ebe5924fe9.png)

In my opinion:
- OCPUE is a register which somehow can control port E pull-up resistors. I found this register's definition in file `lgtx8e.h`, next to port E definition.
- LDOCR is could be a register which may control the internal LDO (Low-Dropout Regulator). VSELx bits may select the LDO output voltage, and PDEN bit disable the LDO.

**Comment by jayzakk** [comment]
OCPUE may be related to this part of the datasheet, which tries to explain all that pin multiplexing shi.. uhm... features:

![grafik](https://user-images.githubusercontent.com/4440984/107851700-25562e80-6e0c-11eb-85a4-a73adba765a6.png)

PUOE - Pull-up multiplexing enable
If this bit is 1, the pull-up enable is controlled by PVOV; if this bit is 0, the pull-up enable is controlled by DDxn, PORTxn and PUD

PUOV - Pull up multiplexing value
If PUOE is 1, this bit is 1 to enable the pin's pull-up resistor, otherwise it will disable the pin's pull-up resistor

The LGT8-**D** datasheet has some interesting relation-tables, which are missing in the **P** datasheet. They may help sort out things:
![grafik](https://user-images.githubusercontent.com/4440984/107852122-276dbc80-6e0f-11eb-880b-67ea2eb34604.png)

But it does NOT conain a registern named OCPUE (but also LDOCR, without any description).

**Comment by LaZsolt** [comment]
This discussion moved here: https://github.com/dbuezas/lgt8fx/discussions/81#discussion-3222825
