### ISSUE TITLE
Repo download doesn't give the latest master version + clean up older zips

### ISSUE THREAD

**Issue by 5chufti** [dbuezas/lgt8fx#82]
maybe I am stupid or ignorant about githubs features but on all other repositories when I go to download I get the current master branch. For this repo I only get the old 1.0.6 release.
and btw, is it necessary to bloat the download with all the old version .zip archives?
as old versions are allways available via the releases section, or no?

**Comment by LaZsolt** [comment]
I think something not workig good.
I did a synchronize my fork with the dbuzeas/lgt8fx repository. (I don't know how, because now I can't find any button for this function) After synchronize, a message appeared in the same line with the synchronized item:
![kép](https://user-images.githubusercontent.com/60486174/108050309-bb2acd00-7049-11eb-82ae-dfff16bbe53c.png)

After that I modified 2 files and create a pull request. The github system did not consider the synchronized items.

**Comment by LaZsolt** [comment]
And the dowload of master behaved the same as at you did. I was suprised.

**Comment by dbuezas** [comment]
You are right with the full branch download, that surprises me also. Maybe it is linked to releases?
I also agree with cleaning up the older zips from the repo.

**Comment by dbuezas** [comment]
It looks like I had a tag called master (like the branch), I deleted it now and this issue should be solved.
